<?php

namespace Metinet\Bundle\FacebookBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerRepository extends EntityRepository
{
    
    /**
     * Fonction qui retourne une Answer à la Question répondue par l'User
     * @param QUESTION $question
     * @param USER $user 
     * @return ANSWER Objet Answer
     */
    public function getUserAnswer($question, $user){
	$paramArray = array();
	$paramArray["question"] = $question;
	$paramArray["user"] = $user;
	// requete DQL
	$result = $this->_em->createQuery("SELECT answer
					FROM MetinetFacebookBundle:Answer answer
					LEFT JOIN answer.users user
					WHERE answer.question = :question
					AND user = :user")
		->setParameters($paramArray)
		->getResult();
	return $result[0];
    }
}
