<?php

namespace Metinet\Bundle\FacebookBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QuizzRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizzRepository extends EntityRepository
{

    /**
     * Fonction qui retourne le nombre de quizz disponible
     * @return INT Le nombre de quizz disponibles
     */
    public function getNombreQuizzDisponibles(){
	return $this->_em->createQuery("SELECT COUNT(quizz.id)
					FROM MetinetFacebookBundle:Quizz quizz")
		->getSingleScalarResult();
    }
    
}
